### ISSUE TITLE
current PKGBUILD does not match upstream

### ISSUE THREAD

**Issue by bill-auger** [fa7ad/av-caster-aur#2]
i noticed you updated this today but you did not update the license in either the PKGBUILD or SRCINFO files or on the AUR webpage - the main reason for the latest update was to change the license to GPL but i also re-worded the description - besides a bugfix for ubuntu there is nothing new in this version - ideally on the next version update could you recreate this repo fresh if thats not too troublesome and start with an initial commit based on the current version

i will be maintaining the PKGBUILD files so you should never need to edit this manually - you could simply fetch the latest version whenever it changes

```
wget https://raw.githubusercontent.com/bill-auger/av-caster/master/Builds/Packaging/PKGBUILD
```

also im not sure what the keywords on the AUR webpage are for but i would think that 'gstreamer' and 'livecoding' are probably not useful - 'livecoding' is the name of one of the hosts it can stream to but that is an confusing name because actually livecoding already is a well-defined term related to music performance (e.g. laptop orchestras) - these keywords are likely related to some search feature so perhaps some better keywords would be of the sort: screencast, webcast, screen capture, vlogging, webcam streaming

**Comment by bill-auger** [comment]
no rush btw - ive since noticed the internal app version did not get updated properly - i have been tending mostly to housekeeping tasks lately and i will probably have a new version ready in a few days (perhaps even a new minor version) if you just want to wait until then

**Comment by fa7ad** [comment]
I'll just bump the release number then
